
variable "client_id" {
  type    = string
  default = "${env("ARM_CLIENT_ID")}"
}

variable "client_secret" {
  type    = string
  default = "${env("ARM_CLIENT_SECRET")}"
}

variable "gallery_name" {
  type    = string
  default = "${env("ARM_GALLERY_NAME")}"
}

variable "resource_group" {
  type    = string
  default = "${env("ARM_IMAGE_RESOURCEGROUP_ID")}"
}

variable "subscription_id" {
  type    = string
  default = "${env("ARM_SUBSCRIPTION_ID")}"
}

source "azure-chroot" "autogenerated_1" {
  client_id     = "${var.client_id}"
  client_secret = "${var.client_secret}"
  shared_image_destination {
    exclude_from_latest = false
    gallery_name        = "${var.gallery_name}"
    image_name          = "MyUbuntuOSImage"
    image_version       = "1.0.0"
    resource_group      = "${var.resource_group}"
    target_regions {
      name                 = "eastus"
      replicas             = "1"
      storage_account_type = "standard_zrs"
    }
  }
  source          = "Canonical:UbuntuServer:20.04-LTS:latest"
  subscription_id = "${var.subscription_id}"
}

build {
  sources = ["source.azure-chroot.autogenerated_1"]

  provisioner "shell" {
    inline         = ["apt update", "apt upgrade -y"]
    inline_shebang = "/bin/sh -x"
  }

}
