# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# This is an example goreleaser.yaml file with some defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
env:
  - CGO_ENABLED=0
before:
  hooks:
    # We strongly recommend running tests to catch any regression before release.
    # Even though, this an optional step.
    - go test ./...
    # Check plugin compatibility with required version of the Packer SDK
    - make plugin-check
    # Copy LICENSE file for inclusion in zip archive
    - cp LICENSE LICENSE.txt
builds:
  # A separated build to run the packer-plugins-check only once for a linux_amd64 binary
  -
    id: plugin-check
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.VersionPrerelease= '
    goos:
      - linux
    goarch:
      - amd64
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
  -
    id: other-builds
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    ldflags:
      - '-s -w -X {{ .ModulePath }}/version.Version={{.Version}} -X {{ .ModulePath }}/version.VersionPrerelease= '
    goos:
      - windows
    goarch:
      - amd64
      - '386'
      - arm
    ignore:
      - goos: windows
        goarch: arm
    binary: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
archives:
- format: zip
  files:
    - "LICENSE.txt"
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Env.API_VERSION }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - cmd: signore
    args: ["sign", "--dearmor", "--file", "${artifact}", "--out", "${signature}"]
    artifacts: checksum
    signature: ${artifact}.sig

changelog:
  use: github-native
